export { getPackageVersion } from "./version.js";
export { redactSecrets } from "./util/redact.js";
export { startCaptureServer } from "./capture/server.js";
export type { CaptureServer, CaptureServerOptions } from "./capture/server.js";
export { transcribeWithWhisper } from "./stt/whisper.js";
export type { WhisperResult, WhisperTranscribeOptions } from "./stt/whisper.js";
export { translateWithClaude } from "./translate/claude.js";
export type { ClaudeTranslateOptions, ClaudeTranslateResult } from "./translate/claude.js";
export { runCapture } from "./commands/capture.js";
export { runTranscribe } from "./commands/transcribe.js";
export { runTranslate } from "./commands/translate.js";
export { runPipeline } from "./commands/run.js";
export type { PipelineResult, RunPipelineOptions } from "./commands/run.js";
